stages:
  load_data:
    cmd: python src/stage_01_load_and_save.py --config=params.yaml
    deps:
      - src/stage_01_load_and_save.py
    params:
      - data_source.uci_source 
      - artifacts.raw_local_data # another parameter upon which this stage depends. Can add more parameters below
    outs:
      - artifacts/raw_local_data_dir/data.csv

  split_data:
    cmd: python src/stage_02_split_data.py --config=params.yaml
    deps:
      - src/stage_02_split_data.py
      - artifacts/raw_local_data_dir/data.csv
    params:
      - base.random_state
      - base.test_size
      - artifacts.raw_local_data # another parameter upon which this stage depends. Can add more parameters below
      - artifacts.split_data.processed_data_dir
      - artifacts.split_data.train_path
      - artifacts.split_data.test_path
    outs:
      - artifacts/processed_data/train.csv
      - artifacts/processed_data/test.csv



  train:
    cmd: python src/stage_03_train.py --config=params.yaml
    deps:
      - src/stage_03_train.py
      - artifacts/processed_data/train.csv
      - src/utils/common_utils.py
    params:
      - base.random_state
      - base.target_col
      - artifacts.split_data.train_path           # another parameter upon which this stage depends. Can add more parameters below
      - estimators.ElasticNet.params.alpha
      - estimators.ElasticNet.params.l1_ratio
    metrics:                                      # instead of report we used name as metrics
      - artifacts/report/params.json:             # accessing the params.json so that we can set cache = False
          cache: false                            # in case some error occurs about cache then run the command suggested.
    outs:
      - artifacts/saved_models/model.joblib


  evaluate:
    cmd: python src/stage_04_evaluate.py --config=params.yaml
    deps:
      - src/stage_04_evaluate.py
      - artifacts/processed_data/test.csv
      - artifacts/saved_models/model.joblib
    params:
      - base.target_col
      - artifacts.split_data.test_path     
    metrics:                                      # instead of report we used name as metrics
      - artifacts/report/scores.json:             # accessing the params.json so that we can set cache = False
          cache: false                            # in case some error occurs about cache then run the command suggested.
